import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// components
import Navbar from '../components/Navbar.tsx';

// Import del font (opzionale)
const inter = Inter({ subsets: ["latin"] });

// Metadati globali del sito
export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

// Layout principale (root)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

